#!/usr/bin/python3
#~/anaconda3/bin/python

import dash_html_components as html
import dash_core_components as dcc
import app_dropdown_values as dv
import os
#to get the login stuff, I might need to add to the header div...

def serve_layout():
    return html.Div(children=[html.Div(children=[html.H1(children=['YULArchivesSpace Toolkit'], className='header-label'),
        html.Div(children=[dcc.Tabs(
            id='all-tabs',
            className='tab_container',
            value='report_tab',
            children=[
                dcc.Tab(
                    label='Reports',
                    value='report_tab',
                    className='custom-tab',
                    selected_className='custom-tab--selected',
                    children=[html.Div(children=[html.Div(children=html.P('View and download reports on various ArchivesSpace data points.', className='directions')),
                                                html.Div(children=[html.Div(children=[dcc.Dropdown(id="query_type_dropdown",
                                                                                multi=False,
                                                                                placeholder='Select a report category',
                                                                                options=[{"label": i, "value": i} for i in dv.query_categories], className='drop')], className='dropdown'),
                                                                   html.Div(children=[dcc.Dropdown(id="selected_query_dropdown",
                                                                                multi=False,
                                                                                placeholder='Select a query to run', className='drop')], className='dropdown'),
                                                                   html.Div(children=html.Div(id='input_div', className='dropdown'), className='parent_input')], className='dropdown_container'),
                                                html.Div(children=[html.Button('Go', id='go_time_query', n_clicks=0, className='api-button')],
                                                         className='button-div'),
                                                html.Div(id='test_div', style={'display': 'none'}),
                                                dcc.Store(id='input_options', storage_type="memory"),
                                                dcc.Store(id='bulk_csv_file', storage_type="memory"),
                                                dcc.Store(id='query_result', storage_type="memory"),
                                                dcc.Store(id='unzipped_datastore', storage_type='memory'),
                                                html.Div(children=html.H5(id='query_description'), className='query-desc'),
                                                html.Div(children=[html.Div(id='number-of-results', className='result-total'),
                                                                    html.Div(id='download-link', className='download-button')]),
                                                html.Div(className='divider'),
                                                html.Div(id="stat_graph_div"),
                                                html.Div(id='query_table', className='query_table_div')], className='body_div')]),
                dcc.Tab(
                    label='Templates',
                    value='template_tab',
                    className='custom-tab',
                    selected_className='custom-tab--selected',
                    children=[html.Div(children=[html.Div(children=html.P('View and download schema templates for all ArchivesSpace record types.', className='directions')),
                                                html.Div(children=[html.Div(children=[dcc.Dropdown(id="schema_dropdown",
                                                                                multi=False,
                                                                                placeholder='Select a schema', className='drop')], className='dropdown')], className='dropdown_container'),
                                                dcc.Store(id='as_templates_store', storage_type='memory'),
                                                html.Div(children=dcc.RadioItems(id="template_options_radio",
                                                                                 options=dv.template_options,
                                                                                value='added_value',
                                                                                labelStyle={'display': 'inline-block', 'padding-left': '5px', 'padding-right': '20px'}), className='api_checklist'),
                                                html.Div(children=[html.Div(className='divider'),
                                                                   html.Button('Go', id='go_time_schema', n_clicks=0, className='api-button')], className='button-div'),
                                                html.Div(id='download_links', className='download-button'),
                                                html.Div(children=[html.Div(className='divider'),
                                                html.Table(id='json_table', className='query-table')]),
                                                html.Pre(id='template_table', className='template-display')], className='body_div')]),
                dcc.Tab(
                    label='Bulk Operations',
                    value='bulk_tab',
                    className='custom-tab',
                    selected_className='custom-tab--selected',
                    children=[html.Div(children=[html.Div(children=[html.P('Create, read, update, and delete ArchivesSpace records in bulk.')], className='directions'),
                                                html.Div(children=dcc.RadioItems(id="api_instance_checklist",
                                                                        options=dv.archivesspace_instances,
                                                                        labelStyle={'display': 'inline-block', 'padding-left': '5px', 'padding-right': '20px'}), className='api_checklist'),
                                                  html.Div([dcc.Input(placeholder='username', id='username_input', type='text', className='login_input'),
                                                         html.Div(className='divider'),
                                                         dcc.Input(placeholder='password', id='password_input', type='password', className='login_input'),
                                                         html.Div(className='divider'),
                                                         html.Button('Submit', id='login_button', type='submit', className='api-button')], className='dropdown'),
                                                    html.Div(children=[html.Div(children=[dcc.Dropdown(id="bulk_operation_category_dropdown",
                                                                                multi=False,
                                                                                placeholder='Select a category',
                                                                                options=[{"label": i.replace('_', ' ').capitalize(), "value": i} for i in dv.bulk_operation_categories], className='drop')], className='dropdown'),
                                                                    # html.Div(children=[dcc.Dropdown(id='function_subcategory_dropdown',
                                                                    #                                 multi=False,
                                                                    #                                 placeholder='Select a subcategory',
                                                                    #                                 options=[{"label": i.replace('_', ' ').capitalize(), "value": i} for i in rend.get_function_subcategories()]
                                                                    #                                 )], className='dropdown'),
                                                                    html.Div(children=[dcc.Dropdown(id="function_dropdown",
                                                                                           multi=False,
                                                                                           placeholder='Select an operation', className='drop')], className='dropdown'),
                                                                    html.Div(children=[dcc.Dropdown(id="input_file_dropdown",
                                                                                           multi=False,
                                                                                           placeholder='Select an input file',
                                                                                           options=[{"label": i, "value": 'data/api_inputs/' + i} for i in os.listdir('data/api_inputs')], className='drop')], className='dropdown'),
                                                                    html.Div(children=[dcc.Dropdown(id="backup_folder_dropdown",
                                                                                           multi=False,
                                                                                           placeholder='Select a backup directory',
                                                                                           options=[{"label": i, "value": 'data/json_backups/' + i} for i in next(os.walk('data/json_backups'))[1]], className='drop')], className='dropdown')], className='dropdown_container'),
                                                html.Div(children=[dcc.ConfirmDialogProvider(
                                                                        children=html.Button('Go', id='go_time', n_clicks=0, className='api-button'),
                                                                        id='are_you_surrre',
                                                                        message='With great power comes great responsibility! Are you sure you want to do this?'),
                                                                   #html.Div(className='divider'),
                                                                   html.Button('Stop', id='stop_time',
                                                                                       n_clicks=0,
                                                                    className='api-button')], className='button-div'),
                                                html.Div(children=[html.H5(id='operation-docs', className='query-desc'),
                                                                   html.Pre(id='api_table', className='doc-table')]),
                                                dcc.Store(id='selected_0', storage_type="memory"),
                                                dcc.Store(id='selected_1', storage_type="memory"),
                                                dcc.Store(id='selected_2', storage_type="memory"),
                                                dcc.Store(id='output-storage', storage_type="memory"),
                                                dcc.Store(id='session_store', storage_type='session'),
                                                dcc.Store(id='object_store', storage_type='session'),
                                                html.Div(id='display_log', className='display-log'),
                                                dcc.Interval(id='log-update', interval=20000000, n_intervals=0)], className='body_div')])])], className='tab_div_container'),
         html.Footer(children=[html.Div(children=[html.A('Yale', href='https://archives.yale.edu', target='_blank', className='yale_footer'),
                                                  html.A('Contact', href='mailto:alicia.detelich@yale.edu', target='_blank', className='footer_links'),
                                                  html.A('Help', href='https://aspace-tools.readthedocs.io/en/latest/', target='_blank', className='footer_links')],
                                        className='footer_div_style')], className='footer_style')], className='app_container')])
